# Generated by Django 5.0 on 2023-12-24 15:04

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('country', models.CharField(max_length=300, verbose_name='страна')),
                ('city', models.CharField(max_length=200, verbose_name='город')),
                ('street', models.CharField(max_length=250, verbose_name='улица')),
                ('house_number', models.PositiveIntegerField(verbose_name='номер дома')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_type', models.CharField(choices=[('factory', 'завод'), ('retailer', 'розничная сеть'), ('sole_proprietor', 'индивидуальный предприниматель')], max_length=50, verbose_name='поставщик')),
                ('title', models.CharField(max_length=300, verbose_name='название')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='дата и время создания')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('contacts', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplier', to='sales_chain.contacts', verbose_name='контакты')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='заказчик', to='sales_chain.supplier', verbose_name='поставщик')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='название')),
                ('model', models.CharField(max_length=100, verbose_name='модель')),
                ('market_launch_date', models.DateTimeField(verbose_name='дата выхода на рынок')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='дата и время создания')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='sales_chain.supplier', verbose_name='поставщик')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='долг')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='дата и время создания')),
                ('creditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debtors', to='sales_chain.supplier', verbose_name='кредитор')),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditors', to='sales_chain.supplier', verbose_name='должник')),
            ],
            options={
                'verbose_name': 'Задолженность',
                'verbose_name_plural': 'Задолженности',
            },
        ),
    ]
