# Generated by Django 5.0 on 2023-12-25 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_chain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='supplier_type',
            field=models.CharField(choices=[('завод', 'завод'), ('розничная сеть', 'розничная сеть'), ('индивидуальный предприниматель', 'индивидуальный предприниматель')], max_length=50, verbose_name='поставщик'),
        ),
    ]
