# Generated by Django 5.0 on 2023-12-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_chain', '0002_alter_supplier_supplier_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='market_launch_date',
            field=models.DateField(verbose_name='дата выхода на рынок'),
        ),
    ]
